/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.EnderecoVO;
import model.FuncionarioVO;
import model.TelefoneVO;
import services.EnderecoServicos;
import services.FuncionarioServicos;
import services.TelefoneServicos;
import util.SessaoUsuario;

/**
 *
 * @author Felipe Remus
 */
public class GUIFuncionario extends javax.swing.JInternalFrame {
    private List<Integer> idsFuncionarios = new ArrayList<>();
    private int idFuncionarioEmEdicao = -1;
    
    private GUIMenuPrincipal menuPrincipal;
    
    DefaultTableModel dtm = new DefaultTableModel(
            new Object [][]{},
            new Object[]{"Nome", "Email", "Telefone", "Rua", "Número", "Bairro", "Cidade", "CEP"}
    );
    /**
     * Creates new form GUIFuncionario
     */
    public GUIFuncionario() {
        initComponents();
        
        
        preencherTabela();
        
        jbtnAlterar.setEnabled(false);
    }
    
    public GUIFuncionario(GUIMenuPrincipal menu) {
        this();
        this.menuPrincipal = menu;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfTelefone = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jtfBairro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtfRua = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtfNumero = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtfComplemento = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtfCidade = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtfCEP = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jtfPesquisar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtFuncionario = new javax.swing.JTable();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jbtnCadastrar = new javax.swing.JButton();
        jbtnLimpar = new javax.swing.JButton();
        jbtnAlterar = new javax.swing.JButton();
        jbtnDeletar = new javax.swing.JButton();
        jbtnPreencher = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Funcionários");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Funcionario.png"))); // NOI18N
        jLabel1.setText("Funcionário");
        jLabel1.setToolTipText("");

        jPanel1.setBackground(new java.awt.Color(255, 195, 66));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nome:");

        jtfNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Email:");

        jtfEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtfEmail.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Telefone:");

        try {
            jtfTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ## ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfTelefone.setText("(          -    ");
        jtfTelefone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Bairro:");

        jtfBairro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtfBairro.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Rua:");

        jtfRua.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtfRua.setToolTipText("");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Numero:");

        jtfNumero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtfNumero.setToolTipText("");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Complemento:");

        jtfComplemento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtfComplemento.setToolTipText("");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Cidade:");

        jtfCidade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtfCidade.setToolTipText("");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("CEP:");

        try {
            jtfCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfCEP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfRua, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jtfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jtfRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jtfCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jtfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(66, 66, 66))
        );

        jTabbedPane1.addTab("Cadastro", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 195, 66));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Nome:");

        jtfPesquisar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtfPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfPesquisarKeyReleased(evt);
            }
        });

        jtFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Email", "Telefone", "Rua", "Número", "Bairro", "Cidade", "CEP"
            }
        ));
        jScrollPane1.setViewportView(jtFuncionario);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(628, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jtfPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Manutenção", jPanel2);

        jbtnCadastrar.setBackground(new java.awt.Color(255, 195, 66));
        jbtnCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cadastrar.png"))); // NOI18N
        jbtnCadastrar.setText("Cadastrar");
        jbtnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCadastrarActionPerformed(evt);
            }
        });
        jbtnCadastrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtnCadastrarKeyPressed(evt);
            }
        });

        jbtnLimpar.setBackground(new java.awt.Color(255, 195, 66));
        jbtnLimpar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Limpar.png"))); // NOI18N
        jbtnLimpar.setText("Limpar");
        jbtnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLimparActionPerformed(evt);
            }
        });
        jbtnLimpar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtnLimparKeyPressed(evt);
            }
        });

        jbtnAlterar.setBackground(new java.awt.Color(255, 195, 66));
        jbtnAlterar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Alterar.png"))); // NOI18N
        jbtnAlterar.setText("Alterar");
        jbtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAlterarActionPerformed(evt);
            }
        });

        jbtnDeletar.setBackground(new java.awt.Color(255, 195, 66));
        jbtnDeletar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Deletar.png"))); // NOI18N
        jbtnDeletar.setText("Deletar");
        jbtnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeletarActionPerformed(evt);
            }
        });

        jbtnPreencher.setBackground(new java.awt.Color(255, 195, 66));
        jbtnPreencher.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnPreencher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Preencher.png"))); // NOI18N
        jbtnPreencher.setText("Preencher");
        jbtnPreencher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPreencherActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(jbtnCadastrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jbtnLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jbtnAlterar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jbtnDeletar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jbtnPreencher, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(jbtnCadastrar)
                .addGap(18, 18, 18)
                .addComponent(jbtnLimpar)
                .addGap(18, 18, 18)
                .addComponent(jbtnPreencher)
                .addGap(18, 18, 18)
                .addComponent(jbtnAlterar)
                .addGap(18, 18, 18)
                .addComponent(jbtnDeletar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnCadastrar)
                    .addComponent(jbtnLimpar)
                    .addComponent(jbtnAlterar)
                    .addComponent(jbtnDeletar)
                    .addComponent(jbtnPreencher))
                .addGap(0, 25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane1)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Método para abrir cadastro de login após cadastrar funcionário
    private void abrirTelaCadastroLogin(String emailFuncionario) {
        try {
            if (menuPrincipal == null) {
                JOptionPane.showMessageDialog(this, "Erro: Menu principal não disponível.");
                return;
            }

            boolean usuarioLogadoEhAdmin = SessaoUsuario.isAdministrador();
            GUICadManuLogin guiLogin = new GUICadManuLogin(menuPrincipal, emailFuncionario, usuarioLogadoEhAdmin);

            JDesktopPane desktop = menuPrincipal.getDesktop();
            desktop.add(guiLogin);
            guiLogin.setVisible(true);
            guiLogin.toFront();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao abrir cadastro de login: " + e.getMessage());
        }
    }

    private void cadastrarFuncionario() {
        try {
            String emailFuncionario = jtfEmail.getText().trim();
            if (emailFuncionario.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Informe o e-mail do funcionário!");
                return;
            }
            
            // Telefone
            TelefoneVO tVO = new TelefoneVO();
            tVO.setFone(jtfTelefone.getText());
            TelefoneServicos ts = services.ServicosFactory.getTelefoneServicos();
            ts.cadadtrarTelefone(tVO);
            int id_fone = ts.getidTelefone(tVO);

            // Endereço
            EnderecoVO eVO = new EnderecoVO();
            eVO.setRua(jtfRua.getText());
            eVO.setNumero(jtfNumero.getText());
            eVO.setComplemento(jtfComplemento.getText());
            eVO.setBairro(jtfBairro.getText());
            eVO.setCidade(jtfCidade.getText());
            eVO.setCep(jtfCEP.getText());
            EnderecoServicos es = services.ServicosFactory.getEnderecoServicos();
            es.cadadtrarEndereco(eVO);
            int id_endereco = es.getidEndereco(eVO);

            // Funcionário
            FuncionarioVO fVO = new FuncionarioVO();
            fVO.setNome_funcionario(jtfNome.getText());
            fVO.setEmail_funcionario(emailFuncionario);
            FuncionarioServicos fs = services.ServicosFactory.getFuncionarioServicos();
            fs.cadastrarFuncionario(fVO, id_fone, id_endereco);

            JOptionPane.showMessageDialog(null, "Funcionário cadastrado com sucesso!");
            
            abrirTelaCadastroLogin(emailFuncionario);
            
            limpar();
            preencherTabela();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar: " + e.getMessage());
        }
    }

    private void preencherTabela() {
        try {
            dtm.setNumRows(0);
            idsFuncionarios.clear();

            FuncionarioServicos fs = services.ServicosFactory.getFuncionarioServicos();
            TelefoneServicos ts = services.ServicosFactory.getTelefoneServicos();
            EnderecoServicos es = services.ServicosFactory.getEnderecoServicos();

            ArrayList<FuncionarioVO> funcionarios = fs.buscarFuncionario();

            for (FuncionarioVO f : funcionarios) {
                TelefoneVO tVO = ts.buscarTelefonePorId((int) f.getId_fone());
                EnderecoVO eVO = es.buscarEnderecoPorId((int) f.getId_endereco());

                dtm.addRow(new Object[]{
                    f.getNome_funcionario(),
                    f.getEmail_funcionario(),
                    tVO.getFone(),
                    eVO.getRua(),
                    eVO.getNumero(),
                    eVO.getBairro(),
                    eVO.getCidade(),
                    eVO.getCep()
                });

                idsFuncionarios.add(f.getId_funcionario());
            }
            jtFuncionario.setModel(dtm);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao preencher tabela: " + e.getMessage());
        }
    }
    
    private void filtrar() {
        try {
            String nome = jtfPesquisar.getText().trim();
            dtm.setNumRows(0);
            idsFuncionarios.clear();

            if (nome.isEmpty()) {
                preencherTabela();
            } else {
                FuncionarioServicos fs = services.ServicosFactory.getFuncionarioServicos();
                TelefoneServicos ts = services.ServicosFactory.getTelefoneServicos();
                EnderecoServicos es = services.ServicosFactory.getEnderecoServicos();

                String query = "WHERE nome_funcionario LIKE '%" + nome + "%'";
                ArrayList<FuncionarioVO> funcionarios = fs.filtrarFuncionario(query);

                for (FuncionarioVO f : funcionarios) {
                    TelefoneVO tVO = ts.buscarTelefonePorId((int) f.getId_fone());
                    EnderecoVO eVO = es.buscarEnderecoPorId((int) f.getId_endereco());

                    String enderecoCompleto = String.format("%s, %s - %s, %s",
                        eVO.getRua(), eVO.getNumero(), eVO.getBairro(), eVO.getCidade()
                    );
                    if (eVO.getComplemento() != null && !eVO.getComplemento().isEmpty()) {
                        enderecoCompleto += " (" + eVO.getComplemento() + ")";
                    }

                    dtm.addRow(new Object[]{
                        f.getNome_funcionario(),
                        f.getEmail_funcionario(),
                        tVO.getFone(),
                        enderecoCompleto
                    });

                    idsFuncionarios.add(f.getId_funcionario()); // ✅
                }
                jtFuncionario.setModel(dtm);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao filtrar: " + e.getMessage());
        }
    }
    
    private void deletarFuncionario() {
        try {
            int linha = jtFuncionario.getSelectedRow();
            if (linha == -1) {
                JOptionPane.showMessageDialog(this, "Selecione um funcionário!");
                return;
            }

            if (idsFuncionarios.isEmpty() || linha >= idsFuncionarios.size()) {
                JOptionPane.showMessageDialog(this, "Dados inconsistentes.");
                preencherTabela();
                return;
            }

            int id_funcionario = idsFuncionarios.get(linha); 

            int confirm = JOptionPane.showConfirmDialog(this, "Excluir funcionário?", "Confirmação", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                FuncionarioServicos fs = services.ServicosFactory.getFuncionarioServicos();
                fs.deletarFuncionario(id_funcionario);
                JOptionPane.showMessageDialog(this, "Funcionário excluído!");
                preencherTabela();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao deletar: " + e.getMessage());
        }
    }
    
    private void preencherAlterarFuncionario() {
        try {
            int linha = jtFuncionario.getSelectedRow();
            if (linha == -1) {
                JOptionPane.showMessageDialog(this, "Selecione um funcionário!");
                return;
            }

            if (idsFuncionarios.isEmpty() || linha >= idsFuncionarios.size()) {
                JOptionPane.showMessageDialog(this, "Dados inconsistentes.");
                return;
            }

            idFuncionarioEmEdicao = idsFuncionarios.get(linha); 

            jTabbedPane1.setSelectedIndex(0);

            FuncionarioServicos fs = services.ServicosFactory.getFuncionarioServicos();
            FuncionarioVO fVO = fs.buscarFuncionarioPorId(idFuncionarioEmEdicao);

            TelefoneServicos ts = services.ServicosFactory.getTelefoneServicos();
            EnderecoServicos es = services.ServicosFactory.getEnderecoServicos();

            TelefoneVO tVO = ts.buscarTelefonePorId((int) fVO.getId_fone());
            EnderecoVO eVO = es.buscarEnderecoPorId((int) fVO.getId_endereco());

            jtfNome.setText(fVO.getNome_funcionario());
            jtfEmail.setText(fVO.getEmail_funcionario());
            jtfTelefone.setText(tVO.getFone());
            jtfRua.setText(eVO.getRua());
            jtfNumero.setText(eVO.getNumero());
            jtfComplemento.setText(eVO.getComplemento() != null ? eVO.getComplemento() : "");
            jtfBairro.setText(eVO.getBairro());
            jtfCidade.setText(eVO.getCidade());
            jtfCEP.setText(eVO.getCep());

            jbtnCadastrar.setEnabled(false);
            jbtnAlterar.setEnabled(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao preencher: " + e.getMessage());
        }
    }
    
    private void confirmarAlterarFuncionario() {
        try {
            if (idFuncionarioEmEdicao == -1) {
                JOptionPane.showMessageDialog(this, "Nenhum funcionário selecionado para alteração.");
                return;
            }

            String nome = jtfNome.getText().trim();
            String email = jtfEmail.getText().trim();
            if (nome.isEmpty() || email.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Preencha nome e e-mail!");
                return;
            }

            FuncionarioVO fVO = new FuncionarioVO();
            fVO.setNome_funcionario(nome);
            fVO.setEmail_funcionario(email);

            TelefoneVO tVO = new TelefoneVO();
            tVO.setFone(jtfTelefone.getText().trim());

            EnderecoVO eVO = new EnderecoVO();
            eVO.setRua(jtfRua.getText().trim());
            eVO.setNumero(jtfNumero.getText().trim());
            eVO.setComplemento(jtfComplemento.getText().trim());
            eVO.setBairro(jtfBairro.getText().trim());
            eVO.setCidade(jtfCidade.getText().trim());
            eVO.setCep(jtfCEP.getText().trim());

            FuncionarioServicos fs = services.ServicosFactory.getFuncionarioServicos();
            fs.confirmarAlteracao(fVO, tVO, eVO, idFuncionarioEmEdicao); // ✅

            JOptionPane.showMessageDialog(this, "Funcionário alterado com sucesso!");

            limpar();
            idFuncionarioEmEdicao = -1;
            jbtnCadastrar.setEnabled(true);
            jbtnAlterar.setEnabled(false);

            preencherTabela();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao alterar: " + e.getMessage());
        }
    }

    private void limpar() {
        jtfNome.setText(null);
        jtfEmail.setText(null);
        jtfTelefone.setText(null);
        jtfRua.setText(null);
        jtfNumero.setText(null);
        jtfComplemento.setText(null);
        jtfBairro.setText(null);
        jtfCidade.setText(null);
        jtfCEP.setText(null);
        dtm.setNumRows(0);
        jbtnAlterar.setEnabled(false);
        jbtnCadastrar.setEnabled(true);
    }
    
    private void jtfPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPesquisarKeyReleased
        limpar();
        filtrar();
    }//GEN-LAST:event_jtfPesquisarKeyReleased

    private void jbtnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCadastrarActionPerformed
        cadastrarFuncionario();
    }//GEN-LAST:event_jbtnCadastrarActionPerformed

    private void jbtnCadastrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnCadastrarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            cadastrarFuncionario();
        }
    }//GEN-LAST:event_jbtnCadastrarKeyPressed

    private void jbtnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLimparActionPerformed
        limpar();
    }//GEN-LAST:event_jbtnLimparActionPerformed

    private void jbtnLimparKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnLimparKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            limpar();
        }
    }//GEN-LAST:event_jbtnLimparKeyPressed

    private void jbtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAlterarActionPerformed
        confirmarAlterarFuncionario();
    }//GEN-LAST:event_jbtnAlterarActionPerformed

    private void jbtnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeletarActionPerformed
        deletarFuncionario();
    }//GEN-LAST:event_jbtnDeletarActionPerformed

    private void jbtnPreencherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPreencherActionPerformed
        preencherAlterarFuncionario();
    }//GEN-LAST:event_jbtnPreencherActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbtnAlterar;
    private javax.swing.JButton jbtnCadastrar;
    private javax.swing.JButton jbtnDeletar;
    private javax.swing.JButton jbtnLimpar;
    private javax.swing.JButton jbtnPreencher;
    private javax.swing.JTable jtFuncionario;
    private javax.swing.JTextField jtfBairro;
    private javax.swing.JFormattedTextField jtfCEP;
    private javax.swing.JTextField jtfCidade;
    private javax.swing.JTextField jtfComplemento;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfNumero;
    private javax.swing.JTextField jtfPesquisar;
    private javax.swing.JTextField jtfRua;
    private javax.swing.JFormattedTextField jtfTelefone;
    // End of variables declaration//GEN-END:variables
}
