/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.GeneroVO;
import services.GeneroServicos;
import services.ServicosFactory;

/**
 *
 * @author FELIPEREMUSDEALMEIDA
 */
public class GUIGenero extends javax.swing.JInternalFrame {
    private List<Integer> idsGeneros = new ArrayList<>();
    private int idGeneroEmEdicao = -1;
    
    DefaultTableModel dtm = new DefaultTableModel(
            new Object [][]{},
            new Object[]{"Gênero"}
    );
    /**
     * Creates new form GUIGenero
     */
    public GUIGenero() {
        initComponents();
        
        preencherTabela();
        
        jbtnAlterar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jbtnCadastrar = new javax.swing.JButton();
        jbtnLimpar = new javax.swing.JButton();
        jbtnAlterar = new javax.swing.JButton();
        jbtnDeletar = new javax.swing.JButton();
        jbtnPreencher = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jtfGenero = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jtfPesquisar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtGenero = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Genero.jpg"))); // NOI18N
        jLabel1.setText("Gênero");
        jLabel1.setToolTipText("");

        jbtnCadastrar.setBackground(new java.awt.Color(255, 195, 66));
        jbtnCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnCadastrar.setText("Cadastrar");
        jbtnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCadastrarActionPerformed(evt);
            }
        });
        jbtnCadastrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtnCadastrarKeyPressed(evt);
            }
        });

        jbtnLimpar.setBackground(new java.awt.Color(255, 195, 66));
        jbtnLimpar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnLimpar.setText("Limpar");
        jbtnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLimparActionPerformed(evt);
            }
        });
        jbtnLimpar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtnLimparKeyPressed(evt);
            }
        });

        jbtnAlterar.setBackground(new java.awt.Color(255, 195, 66));
        jbtnAlterar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnAlterar.setText("Alterar");
        jbtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAlterarActionPerformed(evt);
            }
        });

        jbtnDeletar.setBackground(new java.awt.Color(255, 195, 66));
        jbtnDeletar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnDeletar.setText("Deletar");
        jbtnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeletarActionPerformed(evt);
            }
        });

        jbtnPreencher.setBackground(new java.awt.Color(255, 195, 66));
        jbtnPreencher.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnPreencher.setText("Preencher");
        jbtnPreencher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPreencherActionPerformed(evt);
            }
        });
        jbtnPreencher.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtnPreencherKeyPressed(evt);
            }
        });

        jLayeredPane1.setLayer(jbtnCadastrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jbtnLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jbtnAlterar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jbtnDeletar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jbtnPreencher, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnCadastrar)
                .addGap(18, 18, 18)
                .addComponent(jbtnLimpar)
                .addGap(18, 18, 18)
                .addComponent(jbtnPreencher)
                .addGap(18, 18, 18)
                .addComponent(jbtnAlterar)
                .addGap(18, 18, 18)
                .addComponent(jbtnDeletar)
                .addGap(73, 73, 73))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnCadastrar)
                    .addComponent(jbtnLimpar)
                    .addComponent(jbtnAlterar)
                    .addComponent(jbtnDeletar)
                    .addComponent(jbtnPreencher))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 195, 66));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Nome do Gênero:");

        jtfGenero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtfGenero.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(105, 105, 105))
        );

        jTabbedPane1.addTab("Cadastro", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 195, 66));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Nome:");

        jtfPesquisar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtfPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfPesquisarKeyReleased(evt);
            }
        });

        jtGenero.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Gênero"
            }
        ));
        jScrollPane1.setViewportView(jtGenero);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfPesquisar)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jtfPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Manutenção", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane1)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarGenero(){     
        try {
            GeneroVO gVO = new GeneroVO();
            
            gVO.setNomegenero(jtfGenero.getText());
            
            GeneroServicos gs = services.ServicosFactory.getGeneroServicos(); 
            
            gs.cadGenero(gVO);
            
            JOptionPane.showMessageDialog(null, "Genero cadastrado com sucesso!");
            
            limpar();
            preencherTabela();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar Genero.GUIGenero: " + e.getMessage());
        }        
    }
        
    private void preencherTabela() {
        try {
            dtm.setNumRows(0);
            idsGeneros.clear();

            GeneroServicos gs = ServicosFactory.getGeneroServicos();
            ArrayList<GeneroVO> generos = gs.buscarGenero();

            for (GeneroVO g : generos) {
                dtm.addRow(new Object[]{ g.getNomegenero() });
                idsGeneros.add(g.getIdgenero());
            }
            jtGenero.setModel(dtm);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar gêneros: " + e.getMessage());
        }
    }    
    
    private void filtrar() {
        try {
            String termo = jtfPesquisar.getText().trim();
            dtm.setNumRows(0);
            idsGeneros.clear();

            if (termo.isEmpty()) {
                preencherTabela();
            } else {
                GeneroServicos gs = ServicosFactory.getGeneroServicos();
                ArrayList<GeneroVO> generos = gs.filtarGenero(termo); // (obs: "filtar" → talvez "filtrar"?)

                for (GeneroVO g : generos) {
                    dtm.addRow(new Object[]{ g.getNomegenero() });
                    idsGeneros.add(g.getIdgenero());
                }
                jtGenero.setModel(dtm);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao filtrar gêneros: " + e.getMessage());
        }
    }
    
    private void deletarGenero() {
        try {
            int linha = jtGenero.getSelectedRow();
            if (linha == -1) {
                JOptionPane.showMessageDialog(this, "Selecione um gênero!");
                return;
            }

            if (idsGeneros.isEmpty() || linha >= idsGeneros.size()) {
                JOptionPane.showMessageDialog(this, "Dados inconsistentes.");
                preencherTabela();
                return;
            }

            int idgenero = idsGeneros.get(linha);

            int confirma = JOptionPane.showConfirmDialog(this, "Excluir este gênero?", "Confirmação", JOptionPane.YES_NO_OPTION);
            if (confirma == JOptionPane.YES_OPTION) {
                GeneroServicos gs = ServicosFactory.getGeneroServicos();
                gs.deletarGenero(idgenero);
                JOptionPane.showMessageDialog(this, "Gênero excluído!");
                preencherTabela();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao deletar gênero: " + e.getMessage());
        }
    }
    
    private void PreencherAlterarGenero() {
        try {
            int linha = jtGenero.getSelectedRow();
            if (linha == -1) {
                JOptionPane.showMessageDialog(this, "Selecione um gênero!");
                return;
            }

            if (idsGeneros.isEmpty() || linha >= idsGeneros.size()) {
                JOptionPane.showMessageDialog(this, "Dados inconsistentes.");
                return;
            }

            idGeneroEmEdicao = idsGeneros.get(linha); 

            jTabbedPane1.setSelectedIndex(0);

            GeneroServicos gs = ServicosFactory.getGeneroServicos();
            GeneroVO gVO = gs.buscarGeneroPorId(idGeneroEmEdicao);

            jtfGenero.setText(gVO.getNomegenero());

            jbtnCadastrar.setEnabled(false);
            jbtnAlterar.setEnabled(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao preencher: " + e.getMessage());
        }
    }   
    
    private void ConfirmarAlterarGenero() {
        try {
            if (idGeneroEmEdicao == -1) {
                JOptionPane.showMessageDialog(this, "Nenhum gênero selecionado para alteração.");
                return;
            }

            String nome = jtfGenero.getText().trim();
            if (nome.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Preencha o nome do gênero!");
                return;
            }

            GeneroVO gVO = new GeneroVO();
            gVO.setNomegenero(nome);

            GeneroServicos gs = ServicosFactory.getGeneroServicos();
            gs.confirmarAlteracao(gVO, idGeneroEmEdicao);

            JOptionPane.showMessageDialog(this, "Gênero alterado sucesso!");

            limpar();
            idGeneroEmEdicao = -1;
            jbtnCadastrar.setEnabled(true);
            jbtnAlterar.setEnabled(false);

            preencherTabela();

        } catch (SQLException se) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar alterações: " + se.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro inesperado: " + e.getMessage());
        }
    } 
    
    private void limpar(){
        jtfGenero.setText(null);
        dtm.setNumRows(0);
        jbtnAlterar.setEnabled(false);
        jbtnCadastrar.setEnabled(true);
    }
    
    private void jbtnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCadastrarActionPerformed
        cadastrarGenero();
    }//GEN-LAST:event_jbtnCadastrarActionPerformed

    private void jbtnCadastrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnCadastrarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            cadastrarGenero();
        }
    }//GEN-LAST:event_jbtnCadastrarKeyPressed

    private void jbtnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLimparActionPerformed
        limpar();
    }//GEN-LAST:event_jbtnLimparActionPerformed

    private void jbtnLimparKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnLimparKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            limpar();
        }
    }//GEN-LAST:event_jbtnLimparKeyPressed

    private void jbtnPreencherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPreencherActionPerformed
        PreencherAlterarGenero();
    }//GEN-LAST:event_jbtnPreencherActionPerformed

    private void jbtnPreencherKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnPreencherKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        PreencherAlterarGenero();
        }
    }//GEN-LAST:event_jbtnPreencherKeyPressed

    private void jbtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAlterarActionPerformed
        ConfirmarAlterarGenero();
    }//GEN-LAST:event_jbtnAlterarActionPerformed

    private void jbtnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeletarActionPerformed
        deletarGenero();
    }//GEN-LAST:event_jbtnDeletarActionPerformed

    private void jtfPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPesquisarKeyReleased
        limpar();
        filtrar();
    }//GEN-LAST:event_jtfPesquisarKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbtnAlterar;
    private javax.swing.JButton jbtnCadastrar;
    private javax.swing.JButton jbtnDeletar;
    private javax.swing.JButton jbtnLimpar;
    private javax.swing.JButton jbtnPreencher;
    private javax.swing.JTable jtGenero;
    private javax.swing.JTextField jtfGenero;
    private javax.swing.JTextField jtfPesquisar;
    // End of variables declaration//GEN-END:variables
}
