/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import view.GUIMenuPrincipal;
import java.sql.ResultSet;
import dao.LoginDAO;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.LoginVO;
import services.LoginServicos;
import services.ServicosFactory;
import util.SessaoUsuario;
/**
 *
 * @author FELIPEREMUSDEALMEIDA
 */
public class GUILogin extends javax.swing.JFrame {
    Vector<Integer> codperfil = new Vector<Integer>();
    private boolean modoCliente = false;

    /**
     * Creates new form GUILogin
     */
    public GUILogin() {
        initComponents();
        
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/img/Biblioteca.jpg")).getImage());
        
        restaurarPerfilComboBox();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jbtnLogar = new javax.swing.JButton();
        jbtnCadastrar = new javax.swing.JButton();
        jcdMostrarSenha = new javax.swing.JCheckBox();
        jlPerfil = new javax.swing.JLabel();
        jcbPerfil = new javax.swing.JComboBox<>();
        jlSenha = new javax.swing.JLabel();
        jpfSenha = new javax.swing.JPasswordField();
        jlLogin = new javax.swing.JLabel();
        jtfLogin = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NOME DA BIBLIOTECA");
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel.setBackground(new java.awt.Color(255, 195, 66));

        jbtnLogar.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtnLogar.setText("Logar");
        jbtnLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLogarActionPerformed(evt);
            }
        });
        jbtnLogar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtnLogarKeyPressed(evt);
            }
        });

        jbtnCadastrar.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbtnCadastrar.setText("Cadastrar");
        jbtnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCadastrarActionPerformed(evt);
            }
        });
        jbtnCadastrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtnCadastrarKeyPressed(evt);
            }
        });

        jcdMostrarSenha.setBackground(new java.awt.Color(255, 255, 255));
        jcdMostrarSenha.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jcdMostrarSenha.setText("Mostrar Senha");
        jcdMostrarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcdMostrarSenhaActionPerformed(evt);
            }
        });

        jlPerfil.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jlPerfil.setText("Perfil:");

        jcbPerfil.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jcbPerfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        jcbPerfil.setToolTipText("Selecione...");

        jlSenha.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jlSenha.setText("Senha:");

        jpfSenha.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N

        jlLogin.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jlLogin.setText("Login:");

        jtfLogin.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Login - Biblioteca");

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addContainerGap(439, Short.MAX_VALUE)
                        .addComponent(jbtnLogar)
                        .addGap(71, 71, 71)
                        .addComponent(jbtnCadastrar)
                        .addGap(364, 364, 364))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addComponent(jlSenha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jpfSenha))
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addComponent(jlLogin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfLogin))))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jcdMostrarSenha)
                        .addGap(230, 230, 230)
                        .addComponent(jlPerfil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(443, 443, 443)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlLogin)
                    .addComponent(jtfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSenha)
                    .addComponent(jpfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcdMostrarSenha)
                    .addComponent(jlPerfil)
                    .addComponent(jcbPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnLogar)
                    .addComponent(jbtnCadastrar))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logar() {
        try {
            LoginVO lVO = new LoginVO();
            LoginServicos ls = services.ServicosFactory.getLoginServicos();

            lVO.setLogin(jtfLogin.getText().trim());
            lVO.setSenha(jpfSenha.getText().trim());
            lVO.setPerfil(ls.getPerfil((String) jcbPerfil.getSelectedItem()));

            LoginVO usuarioAutenticado = ls.autenticarLogin(lVO);

            if (usuarioAutenticado != null) {
                SessaoUsuario.setUsuarioLogado(usuarioAutenticado);
                GUIMenuPrincipal gmp = new GUIMenuPrincipal();
                gmp.setVisible(true);
                
                // ✅ Se for cliente, abre diretamente a pesquisa de livros
                if (usuarioAutenticado.getPerfil() == 1) { // ID 1 = Cliente
                    GUILivro guiLivroCliente = new GUILivro(true); // true = modo cliente
                    gmp.jdpAreaDeTrabalho.add(guiLivroCliente);
                    guiLivroCliente.setVisible(true);
                    guiLivroCliente.toFront();
                }
                
                dispose();
            } else {
                // 🔒 Mensagem genérica de segurança
                JOptionPane.showMessageDialog(null, "Login, senha ou perfil inválidos.", 
                    "Erro de Autenticação", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            // 🔒 Também usa mensagem genérica em caso de erro
            JOptionPane.showMessageDialog(null, "Login, senha ou perfil inválidos.", 
                "Erro de Autenticação", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void restaurarPerfilComboBox() {
        try {
            LoginServicos ls = services.ServicosFactory.getLoginServicos();
            List<Map<String, Object>> perfis = ls.listaPerfil();

            jcbPerfil.removeAllItems();
            codperfil.clear();

            for (Map<String, Object> perfil : perfis) {
                codperfil.addElement((Integer) perfil.get("id"));
                jcbPerfil.addItem((String) perfil.get("nome"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar perfis: " + e.getMessage());
        }
    }
    
    private boolean isPrimeiraExecucao() {
        try {
            LoginServicos ls = ServicosFactory.getLoginServicos();
            ArrayList<LoginVO> logins = ls.buscarTodosLogins();
            return logins.isEmpty();
        } catch (Exception e) {
            return true; // Se der erro, assume primeira execução
        }
    }
    
    private void abrirCadastroLogin() {
        try {
            boolean primeiraExecucao = isPrimeiraExecucao();

            // ✅ Abre o Menu Principal Especial
            GUIMenuPrincipalEspecial menuEspecial = new GUIMenuPrincipalEspecial(this, primeiraExecucao);
            menuEspecial.setVisible(true);
            menuEspecial.setExtendedState(JFrame.MAXIMIZED_BOTH);
            this.setVisible(false);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao abrir cadastro: " + e.getMessage());
            e.printStackTrace();
        }
    }
    
    private void jcdMostrarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcdMostrarSenhaActionPerformed
        if(jcdMostrarSenha.isSelected()){
            jpfSenha.setEchoChar((char)0);
        }else{
            jpfSenha.setEchoChar('*');
        }
    }//GEN-LAST:event_jcdMostrarSenhaActionPerformed

    private void jbtnLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLogarActionPerformed
        logar();
    }//GEN-LAST:event_jbtnLogarActionPerformed

    private void jbtnLogarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnLogarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            logar();
        }
    }//GEN-LAST:event_jbtnLogarKeyPressed

    private void jbtnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCadastrarActionPerformed
        abrirCadastroLogin();
    }//GEN-LAST:event_jbtnCadastrarActionPerformed

    private void jbtnCadastrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnCadastrarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            abrirCadastroLogin();
        }
    }//GEN-LAST:event_jbtnCadastrarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUILogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel;
    private javax.swing.JButton jbtnCadastrar;
    private javax.swing.JButton jbtnLogar;
    private javax.swing.JComboBox<String> jcbPerfil;
    private javax.swing.JCheckBox jcdMostrarSenha;
    private javax.swing.JLabel jlLogin;
    private javax.swing.JLabel jlPerfil;
    private javax.swing.JLabel jlSenha;
    private javax.swing.JPasswordField jpfSenha;
    private javax.swing.JTextField jtfLogin;
    // End of variables declaration//GEN-END:variables
}
