/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import model.ClienteVO;
import model.LivroVO;
import model.ReservaVO;
import services.ClienteServicos;
import services.LivroServicos;
import services.ReservaServicos;
import services.ServicosFactory;

/**
 *
 * @author Felipe Remus
 */
public class GUIReserva extends javax.swing.JInternalFrame {
    private List<Integer> idsReservas = new ArrayList<>();
    private int idReservaEmEdicao = -1;
    private GUIMenuPrincipal menuPrincipal;

    DefaultTableModel dtm = new DefaultTableModel(
        new Object[][]{},
        new String[]{"Cliente", "Livro", "Data Reserva", "Status"}
    );

    /**
     * Creates new form GUIReserva
     */
    public GUIReserva() {
        initComponents();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        jtfDataReserva.setText(sdf.format(new Date()));
        jtfDataReserva.setEditable(false);
        jtReserva.setModel(dtm);
        jbtnAlterar.setEnabled(false);
        carregarListasIniciais();
        preencherTabela();
        setupFiltros();
    }
    
    public GUIReserva(GUIMenuPrincipal menu) {
        this();
        this.menuPrincipal = menu;
    }
    

    private void carregarListasIniciais() {
        carregarClientes("");
        carregarLivros("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jtfCliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtfLivro = new javax.swing.JTextField();
        jcbCliente = new javax.swing.JComboBox<>();
        jcbLivro = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jtfDataReserva = new javax.swing.JFormattedTextField();
        jtfEditarData = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jtfPesquisar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtReserva = new javax.swing.JTable();
        jcbStatusFiltro = new javax.swing.JComboBox<>();
        jcbTipoPesquisa = new javax.swing.JComboBox<>();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jbtnCadastrar = new javax.swing.JButton();
        jbtnLimpar = new javax.swing.JButton();
        jbtnAlterar = new javax.swing.JButton();
        jbtnDeletar = new javax.swing.JButton();
        jbtnPreencher = new javax.swing.JButton();
        jbtnEmprestimo = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Reservas");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Reserva.png"))); // NOI18N
        jLabel1.setText("Reserva");
        jLabel1.setToolTipText("");

        jPanel1.setBackground(new java.awt.Color(255, 195, 66));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Cliente:");

        jtfCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtfCliente.setToolTipText("");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Livro:");

        jtfLivro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtfLivro.setToolTipText("");

        jcbCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jcbLivro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Data de Hoje:");

        try {
            jtfDataReserva.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfDataReserva.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jtfEditarData.setText("Editar Data");
        jtfEditarData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfEditarDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfDataReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfEditarData)
                .addGap(322, 322, 322))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfCliente)
                    .addComponent(jcbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcbLivro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtfLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfDataReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfEditarData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jtfLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79))
        );

        jTabbedPane1.addTab("Cadastro", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 195, 66));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Pesquisar:");

        jtfPesquisar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtfPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfPesquisarKeyReleased(evt);
            }
        });

        jtReserva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cliente", "Livro", "Retirada", "Prazo", "Status"
            }
        ));
        jScrollPane1.setViewportView(jtReserva);

        jcbStatusFiltro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jcbStatusFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Ativa", "Concluida", "Cancelada" }));

        jcbTipoPesquisa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jcbTipoPesquisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Livro" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jcbTipoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jcbStatusFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(203, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jtfPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbStatusFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbTipoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Manutenção", jPanel2);

        jbtnCadastrar.setBackground(new java.awt.Color(255, 195, 66));
        jbtnCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cadastrar.png"))); // NOI18N
        jbtnCadastrar.setText("Cadastrar");
        jbtnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCadastrarActionPerformed(evt);
            }
        });
        jbtnCadastrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtnCadastrarKeyPressed(evt);
            }
        });

        jbtnLimpar.setBackground(new java.awt.Color(255, 195, 66));
        jbtnLimpar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Limpar.png"))); // NOI18N
        jbtnLimpar.setText("Limpar");
        jbtnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLimparActionPerformed(evt);
            }
        });
        jbtnLimpar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtnLimparKeyPressed(evt);
            }
        });

        jbtnAlterar.setBackground(new java.awt.Color(255, 195, 66));
        jbtnAlterar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Alterar.png"))); // NOI18N
        jbtnAlterar.setText("Alterar");
        jbtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAlterarActionPerformed(evt);
            }
        });

        jbtnDeletar.setBackground(new java.awt.Color(255, 195, 66));
        jbtnDeletar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cancelar.png"))); // NOI18N
        jbtnDeletar.setText("Cancelar");
        jbtnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeletarActionPerformed(evt);
            }
        });

        jbtnPreencher.setBackground(new java.awt.Color(255, 195, 66));
        jbtnPreencher.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnPreencher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Preencher.png"))); // NOI18N
        jbtnPreencher.setText("Preencher");
        jbtnPreencher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPreencherActionPerformed(evt);
            }
        });

        jbtnEmprestimo.setBackground(new java.awt.Color(255, 195, 66));
        jbtnEmprestimo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnEmprestimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Concluir.png"))); // NOI18N
        jbtnEmprestimo.setText("Concluir");
        jbtnEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEmprestimoActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(jbtnCadastrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jbtnLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jbtnAlterar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jbtnDeletar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jbtnPreencher, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jbtnEmprestimo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnCadastrar)
                .addGap(18, 18, 18)
                .addComponent(jbtnLimpar)
                .addGap(18, 18, 18)
                .addComponent(jbtnPreencher)
                .addGap(18, 18, 18)
                .addComponent(jbtnAlterar)
                .addGap(18, 18, 18)
                .addComponent(jbtnDeletar)
                .addGap(18, 18, 18)
                .addComponent(jbtnEmprestimo)
                .addGap(73, 73, 73))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnCadastrar)
                    .addComponent(jbtnLimpar)
                    .addComponent(jbtnAlterar)
                    .addComponent(jbtnDeletar)
                    .addComponent(jbtnPreencher)
                    .addComponent(jbtnEmprestimo))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane1)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarReserva() {
        try {
            String dataStr = jtfDataReserva.getText().trim();
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            sdf.setLenient(false);
            Date dataReserva = sdf.parse(dataStr);

            if (jcbCliente.getSelectedItem() == null || jcbLivro.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(this, "Selecione cliente e livro!");
                return;
            }

            ClienteVO cliente = (ClienteVO) jcbCliente.getSelectedItem();
            LivroVO livro = (LivroVO) jcbLivro.getSelectedItem();

            LivroServicos ls = ServicosFactory.getLivroServicos();
            ArrayList<LivroVO> livrosDisponiveis = ls.buscarLivrosComFiltro("", "Disponível");
            boolean livroDisponivel = livrosDisponiveis.stream()
                .anyMatch(l -> l.getIdLivro() == livro.getIdLivro());

            if (livroDisponivel) {
                JOptionPane.showMessageDialog(this,
                    "Reserva permitida apenas para livros **indisponíveis**!\n" +
                    "Este livro está disponível para empréstimo.",
                    "Livro Disponível",
                    JOptionPane.WARNING_MESSAGE
                );
                return;
            }

            ReservaVO rVO = new ReservaVO();
            rVO.setDtReserva(dataReserva);
            rVO.setIdCliente((int) cliente.getId_cliente());
            rVO.setIdLivro(livro.getIdLivro());

            ReservaServicos rs = ServicosFactory.getReservaServicos();
            rs.cadastrarReserva(rVO);

            JOptionPane.showMessageDialog(this, "Reserva cadastrada com sucesso!");
            limpar();
            preencherTabela();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar reserva: " + e.getMessage());
        }
    }
    
    private void preencherTabela() {
        try {
            dtm.setNumRows(0);
            idsReservas.clear();

            ReservaServicos rs = ServicosFactory.getReservaServicos();
            ArrayList<ReservaVO> reservas = rs.buscarReservas();

            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            for (ReservaVO r : reservas) {
                String nomeLivroExibicao = r.getNomeLivro();
                try {
                    LivroServicos ls = ServicosFactory.getLivroServicos();
                    LivroVO livroVO = ls.buscarLivroPorId(r.getIdLivro());
                    if (livroVO != null) {
                        nomeLivroExibicao = livroVO.toString();
                    }
                } catch (Exception ex) {
                    nomeLivroExibicao = r.getNomeLivro() + " (erro ao carregar)";
                }

                dtm.addRow(new Object[]{
                    r.getNomeCliente(),
                    nomeLivroExibicao,
                    sdf.format(r.getDtReserva()),
                    r.getStatusReserva()
                });
                idsReservas.add(r.getIdReserva());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao preencher tabela: " + e.getMessage());
        }
    }
    
     private void filtrar() {
        try {
            String termo = jtfPesquisar.getText().trim();
            String tipo = (String) jcbTipoPesquisa.getSelectedItem();
            String statusSelecionado = (String) jcbStatusFiltro.getSelectedItem();
            String statusFiltro = "Todos".equals(statusSelecionado) ? null : statusSelecionado;

            dtm.setNumRows(0);
            idsReservas.clear();

            ReservaServicos rs = ServicosFactory.getReservaServicos();
            ArrayList<ReservaVO> reservas;

            if (termo.isEmpty()) {
                if (statusFiltro == null) {
                    reservas = rs.buscarReservas();
                } else {
                    reservas = rs.buscarReservasPorStatus(statusFiltro);
                }
            } else {
                if ("Cliente".equals(tipo)) {
                    reservas = rs.filtrarPorCliente(termo, statusFiltro);
                } else {
                    reservas = rs.filtrarPorLivro(termo, statusFiltro);
                }
            }

            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            for (ReservaVO r : reservas) {
                String dtReservaStr = r.getDtReserva() != null ? sdf.format(r.getDtReserva()) : "";
                String nomeLivroExibicao = r.getNomeLivro();
                try {
                    LivroServicos ls = ServicosFactory.getLivroServicos();
                    LivroVO livroVO = ls.buscarLivroPorId(r.getIdLivro());
                    if (livroVO != null) {
                        nomeLivroExibicao = livroVO.toString();
                    }
                } catch (Exception ex) {
                    // mantém o nome original
                }
                dtm.addRow(new Object[]{
                    r.getNomeCliente(),
                    nomeLivroExibicao,
                    dtReservaStr,
                    r.getStatusReserva()
                });
                idsReservas.add(r.getIdReserva());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao filtrar: " + e.getMessage());
        }
    }
    
    private void preencherAlterar() {
        try {
            int linha = jtReserva.getSelectedRow();
            if (linha == -1) {
                JOptionPane.showMessageDialog(this, "Selecione uma reserva!");
                return;
            }

            if (idsReservas.isEmpty() || linha >= idsReservas.size()) {
                JOptionPane.showMessageDialog(this, "Dados inconsistentes.");
                return;
            }

            idReservaEmEdicao = idsReservas.get(linha);

            ReservaServicos rs = ServicosFactory.getReservaServicos();
            ReservaVO rVO = rs.buscarReservaPorId(idReservaEmEdicao);

            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            jtfDataReserva.setText(rVO.getDtReserva() != null ? sdf.format(rVO.getDtReserva()) : "");
            jtfDataReserva.setEditable(true);

            carregarClientes("");
            carregarLivros("");

            // Seleciona cliente
            for (int i = 0; i < jcbCliente.getItemCount(); i++) {
                Object item = jcbCliente.getItemAt(i);
                if (item instanceof ClienteVO && ((ClienteVO) item).getId_cliente() == rVO.getIdCliente()) {
                    jcbCliente.setSelectedIndex(i);
                    break;
                }
            }

            // Seleciona livro
            for (int i = 0; i < jcbLivro.getItemCount(); i++) {
                Object item = jcbLivro.getItemAt(i);
                if (item instanceof LivroVO && ((LivroVO) item).getIdLivro() == rVO.getIdLivro()) {
                    jcbLivro.setSelectedIndex(i);
                    break;
                }
            }

            jTabbedPane1.setSelectedIndex(0);
            jbtnCadastrar.setEnabled(false);
            jbtnAlterar.setEnabled(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao preencher dados: " + e.getMessage());
        }
    }
    
     private void confirmarAlterar() {
        try {
            if (idReservaEmEdicao == -1) {
                JOptionPane.showMessageDialog(this, "Nenhuma reserva selecionada para alteração.");
                return;
            }

            String dataReservaStr = jtfDataReserva.getText().trim();
            if (dataReservaStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Preencha a data da reserva!");
                return;
            }

            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            sdf.setLenient(false);
            Date dtReserva = sdf.parse(dataReservaStr);

            ClienteVO cliente = (ClienteVO) jcbCliente.getSelectedItem();
            LivroVO livro = (LivroVO) jcbLivro.getSelectedItem();

            if (cliente == null || livro == null) {
                JOptionPane.showMessageDialog(this, "Selecione cliente e livro!");
                return;
            }

            // ✅ Validar novamente: só permite livros indisponíveis
            LivroServicos ls = ServicosFactory.getLivroServicos();
            ArrayList<LivroVO> livrosDisponiveis = ls.buscarLivrosComFiltro("", "Disponível");
            boolean livroDisponivel = livrosDisponiveis.stream()
                .anyMatch(l -> l.getIdLivro() == livro.getIdLivro());

            if (livroDisponivel) {
                JOptionPane.showMessageDialog(this,
                    "Reserva só pode ser feita para livros indisponíveis!",
                    "Livro Disponível",
                    JOptionPane.WARNING_MESSAGE
                );
                return;
            }
            ReservaVO rVO = new ReservaVO();
            rVO.setIdReserva(idReservaEmEdicao);
            rVO.setDtReserva(dtReserva);
            rVO.setIdCliente((int) cliente.getId_cliente());
            rVO.setIdLivro(livro.getIdLivro());

            ReservaServicos rs = ServicosFactory.getReservaServicos();
            rs.atualizarReserva(rVO);

            JOptionPane.showMessageDialog(this, "Reserva alterada com sucesso!");
            limpar();
            preencherTabela();

        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Formato de data inválido. Use dd/MM/yyyy.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao alterar: " + e.getMessage());
        }
    }
    
    private void cancelarReserva() {
        try {
            int linha = jtReserva.getSelectedRow();
            if (linha == -1) {
                JOptionPane.showMessageDialog(this, "Selecione uma reserva!");
                return;
            }

            if (idsReservas.isEmpty() || linha >= idsReservas.size()) {
                JOptionPane.showMessageDialog(this, "Dados inconsistentes.");
                return;
            }

            int idReserva = idsReservas.get(linha);
            int confirma = JOptionPane.showConfirmDialog(this,
                "Cancelar esta reserva?", "Confirmação", JOptionPane.YES_NO_OPTION);

            if (confirma == JOptionPane.YES_OPTION) {
                ReservaServicos rs = ServicosFactory.getReservaServicos();
                ReservaVO rVO = rs.buscarReservaPorId(idReserva);
                rVO.setStatusReserva("Cancelada");
                rs.atualizarStatusReserva(rVO); 

                JOptionPane.showMessageDialog(this, "Reserva cancelada!");
                preencherTabela();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao cancelar: " + e.getMessage());
        }
    }
    
    private void converterReservaEmEmprestimo() {
        try {
            int linha = jtReserva.getSelectedRow();
            if (linha == -1) {
                JOptionPane.showMessageDialog(this, "Selecione uma reserva!");
                return;
            }

            if (idsReservas.isEmpty() || linha >= idsReservas.size()) {
                JOptionPane.showMessageDialog(this, "Dados inconsistentes.");
                return;
            }

            int idReserva = idsReservas.get(linha);
            ReservaServicos rs = ServicosFactory.getReservaServicos();
            ReservaVO rVO = rs.buscarReservaPorId(idReserva);

            if (!"Ativa".equals(rVO.getStatusReserva())) {
                JOptionPane.showMessageDialog(this, "Apenas reservas 'Ativas' podem ser convertidas.");
                return;
            }

            int confirma = JOptionPane.showConfirmDialog(
                this,
                "Deseja criar um empréstimo para esta reserva?",
                "Confirmar Conversão",
                JOptionPane.YES_NO_OPTION
            );
            if (confirma != JOptionPane.YES_OPTION) {
                return;
            }

            ClienteServicos cs = ServicosFactory.getClienteServicos();
            LivroServicos ls = ServicosFactory.getLivroServicos();
            ClienteVO cliente = cs.buscarClientePorId(rVO.getIdCliente());
            LivroVO livro = ls.buscarLivroPorId(rVO.getIdLivro());

            Runnable callback = () -> SwingUtilities.invokeLater(this::preencherTabela);

            GUIEmprestimo guiEmp = new GUIEmprestimo(cliente, livro, rVO, callback);

            JDesktopPane desktop = (menuPrincipal != null) ? menuPrincipal.getDesktop() : (JDesktopPane) getParent();
            desktop.add(guiEmp);
            guiEmp.setVisible(true);
            guiEmp.toFront();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao preparar conversão: " + e.getMessage());
        }
    }
    
    private void limpar() {
        jtfDataReserva.setText(null);
        jtfCliente.setText(null);
        jtfLivro.setText(null);
        carregarListasIniciais();
        jbtnAlterar.setEnabled(false);
        jbtnCadastrar.setEnabled(true);
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        jtfDataReserva.setText(sdf.format(new Date()));
        jtfDataReserva.setEditable(false);
        preencherTabela();
    }
    
    private void carregarClientes(String filtro) {
        try {
            ClienteServicos cs = ServicosFactory.getClienteServicos();
            String query = "WHERE nome_cliente LIKE '%" + filtro + "%'";
            ArrayList<ClienteVO> clientes = cs.filtrarCliente(query);
            DefaultComboBoxModel<ClienteVO> model = new DefaultComboBoxModel<>();
            for (ClienteVO c : clientes) {
                model.addElement(c);
            }
            jcbCliente.setModel(model);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void carregarLivros(String filtro) {
        try {
            LivroServicos ls = ServicosFactory.getLivroServicos();
            ArrayList<LivroVO> livros;
            if (filtro == null || filtro.trim().isEmpty()) {
                livros = ls.buscarLivros();
            } else {
                livros = ls.filtrarLivrosPorNomeEEdicao(filtro.trim());
            }
            DefaultComboBoxModel<LivroVO> model = new DefaultComboBoxModel<>();
            for (LivroVO l : livros) {
                model.addElement(l);
            }
            jcbLivro.setModel(model);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao carregar livros: " + e.getMessage());
        }
    }
    
    private void setupFiltros() {
        jtfCliente.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void changedUpdate(DocumentEvent e) { carregarClientes(jtfCliente.getText()); }
            @Override
            public void removeUpdate(DocumentEvent e) { carregarClientes(jtfCliente.getText()); }
            @Override
            public void insertUpdate(DocumentEvent e) { carregarClientes(jtfCliente.getText()); }
        });

        jtfLivro.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void changedUpdate(DocumentEvent e) { carregarLivros(jtfLivro.getText()); }
            @Override
            public void removeUpdate(DocumentEvent e) { carregarLivros(jtfLivro.getText()); }
            @Override
            public void insertUpdate(DocumentEvent e) { carregarLivros(jtfLivro.getText()); }
        });

        jtfPesquisar.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void changedUpdate(DocumentEvent e) { filtrar(); }
            @Override
            public void removeUpdate(DocumentEvent e) { filtrar(); }
            @Override
            public void insertUpdate(DocumentEvent e) { filtrar(); }
        });

        jcbTipoPesquisa.addActionListener(e -> filtrar());
        jcbStatusFiltro.addActionListener(e -> filtrar());
    }
    
    private void jtfEditarDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfEditarDataActionPerformed
        jtfDataReserva.setEditable(true);
    }//GEN-LAST:event_jtfEditarDataActionPerformed

    private void jtfPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPesquisarKeyReleased
        limpar();
        filtrar();
    }//GEN-LAST:event_jtfPesquisarKeyReleased

    private void jbtnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCadastrarActionPerformed
        cadastrarReserva();
    }//GEN-LAST:event_jbtnCadastrarActionPerformed

    private void jbtnCadastrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnCadastrarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            cadastrarReserva();
        }
    }//GEN-LAST:event_jbtnCadastrarKeyPressed

    private void jbtnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLimparActionPerformed
        limpar();
    }//GEN-LAST:event_jbtnLimparActionPerformed

    private void jbtnLimparKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnLimparKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            limpar();
        }
    }//GEN-LAST:event_jbtnLimparKeyPressed

    private void jbtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAlterarActionPerformed
        confirmarAlterar();
    }//GEN-LAST:event_jbtnAlterarActionPerformed

    private void jbtnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeletarActionPerformed
        cancelarReserva();
    }//GEN-LAST:event_jbtnDeletarActionPerformed

    private void jbtnPreencherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPreencherActionPerformed
        preencherAlterar();
    }//GEN-LAST:event_jbtnPreencherActionPerformed

    private void jbtnEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEmprestimoActionPerformed
        converterReservaEmEmprestimo();
    }//GEN-LAST:event_jbtnEmprestimoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbtnAlterar;
    private javax.swing.JButton jbtnCadastrar;
    private javax.swing.JButton jbtnDeletar;
    private javax.swing.JButton jbtnEmprestimo;
    private javax.swing.JButton jbtnLimpar;
    private javax.swing.JButton jbtnPreencher;
    private javax.swing.JComboBox<ClienteVO> jcbCliente;
    private javax.swing.JComboBox<LivroVO> jcbLivro;
    private javax.swing.JComboBox<String> jcbStatusFiltro;
    private javax.swing.JComboBox<String> jcbTipoPesquisa;
    private javax.swing.JTable jtReserva;
    private javax.swing.JTextField jtfCliente;
    private javax.swing.JFormattedTextField jtfDataReserva;
    private javax.swing.JButton jtfEditarData;
    private javax.swing.JTextField jtfLivro;
    private javax.swing.JTextField jtfPesquisar;
    // End of variables declaration//GEN-END:variables
}
